# The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
# This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: %ip%

# Port to listen for new votes on
port: 8192

# Enable or disable the debug mode.
debug: true

# Setting this option to true will disable handling of Protocol v1 packets. While the old protocol is not secure, this
# option is currently not recommended as most voting sites only support the old protocol at present. However, if you are
# using NuVotifier's proxy forwarding mechanism, enabling this option will increase your server's security.
disable-v1-protocol: false

# Ignores all votes from players who are not connected to the server.
# This means that if the player is not connected in the mode in which the
# vote has been received, the vote is ignored and does nothing.
ignore-offline-votes: false

# All tokens, labeled by the serviceName of each server list.
tokens:
  # Default token for all server lists, if another isn't supplied.
  default: %default_token%

# Configuration section for all vote forwarding to NuVotifier
forwarding:
  # Sets whether to set up a remote method for fowarding. Supported methods:
  # - none - Does not set up a forwarding method.
  # - pluginMessaging - Sets up plugin messaging.
  # - redis - Sets up redis forwarding.
  method: none
  pluginMessaging:
    channel: nuvotifier:votes
  redis:
    address: 127.0.0.1
    port: 6379
    username: ""
    password: ""
    uri: "" # will have priority over the other options
    channel: nuvotifier:votes